-- TODO: ask about additional exercises, because we're skipping two due to new years stuff
-- TODO: show let where case lambdas
-- TODO: talk about bitvectors, think about whether to change the constructor
