-- TODO: if two functions are nearly the same factor out the common bits!!
-- TODO: project deadlines
--
-- TODO: newtypes
-- TODO: TYPE CLASS ES - eq ((), Bit, nat, bv) ord ((), Bit, nat, bv??!?!),
-- TODO: semigroup, monoid ????? maybe "PLUSSY" hehe
-- TODO: Any, All, Add, Mult, bitvectors, Endo
